version: "2"
plugins:
  rubocop:
    enabled: true
    channel: "rubocop-0-79"
    Documentation:
      Enabled: false
    checks:
      Metrics/LineLength:
        Max: 80
        IgnoredPatterns: ['(\A|\s)#']
exclude_patterns:
  - "db/schema.rb"
  - "Rakefile"
  - "bin/"
  - "config/environments/"
  - "!spec/support/helpers"
