version: "2"
plugins:
  rubocop:
    enabled: true
    channel: "rubocop-0-79"
    checks:
      Rubocop/Style/Documentation:
        Enabled: false
      Rubocop/Metrics/LineLength:
        Max: 80
        IgnoredPatterns: ['^(\s+)?#']
exclude_patterns:
  - "db/schema.rb"
  - "Rakefile"
  - "bin/"
  - "config/"
  - "!spec/support/helpers"
