AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Max: 80
  IgnoredPatterns: ['^(\s+)?#']
