version: "3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/api

  redis:
    image: redis

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env/development/database
    # volumes:
    #   - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
